### ISSUE TITLE
Map: Color-coded pins that indicate space availability

### ISSUE THREAD

**Issue by shawarmashubs** [chalmersproject/chalmers-signal-occupancy#11]
- color coding current capacity visually on map, as received from signals
    - green for empty, yellow for filling up, orange for nearly full, red for full, grey for no updates recently (in last X hours)

**Comment by MisterChalmers** [comment]
- includes live streaming updates of occupancy to map (half/most of the lfit)
- math for colour scheme

**Comment by MisterChalmers** [comment]
I've completed this task!
