### ISSUE TITLE
Map: Popup should include last-measurement timestamp

### ISSUE THREAD

**Issue by shawarmashubs** [chalmersproject/chalmers-signal-occupancy#20]
last updated/timestamp of current capacity change (how recent is the “current capacity” number)

**Comment by MisterChalmers** [comment]
Alternatively, I was thinking "Shelter Signal Location Markers" could change from "coloured" to "grey" after N-hours. Kind of like they've gone stale, grey markers would indicate shelters who haven't updated (one or both of) their capacity metrics in some time.

**Comment by MisterChalmers** [comment]
Similar to this issue: https://github.com/chalmersproject/openshelter/issues/4

**Comment by MisterChalmers** [comment]
Since this is an issue with the webservice, and not the hardware signal, I'm closing this issue.
